const STORAGE_NAME = "@gofinances";

const COLLECTION_USER = `${STORAGE_NAME}:user`;
const COLLECTION_TRANSACTIONS = `${STORAGE_NAME}:transactions`;

export { COLLECTION_USER, COLLECTION_TRANSACTIONS };
